-- Seed Master Libraries element templates from docs/Elements Templete.md.

INSERT INTO public.master_element_templates (element_code, category, element_name, note)
VALUES
  ('STR-001', 'Structure', 'Bored Pile', NULL),
  ('STR-002', 'Structure', 'Driven Pile', NULL),
  ('STR-003', 'Structure', 'Micro Pile', NULL),
  ('STR-004', 'Structure', 'Pile Cap', NULL),
  ('STR-005', 'Structure', 'Raft Foundation', NULL),
  ('STR-006', 'Structure', 'Strip Footing', NULL),
  ('STR-007', 'Structure', 'Pad Footing', NULL),
  ('STR-008', 'Structure', 'Ground Beam', NULL),
  ('STR-009', 'Structure', 'Tie Beam', NULL),
  ('STR-010', 'Structure', 'Foundation Slab', NULL),
  ('STR-011', 'Structure', 'Retaining Wall', NULL),
  ('STR-012', 'Structure', 'Diaphragm Wall', NULL),
  ('STR-013', 'Structure', 'Soldier Pile Wall', NULL),
  ('STR-014', 'Structure', 'Column', NULL),
  ('STR-015', 'Structure', 'Shear Wall', NULL),
  ('STR-016', 'Structure', 'Core Wall', NULL),
  ('STR-017', 'Structure', 'Beam', NULL),
  ('STR-018', 'Structure', 'Transfer Beam', NULL),
  ('STR-019', 'Structure', 'Slab', NULL),
  ('STR-020', 'Structure', 'Flat Slab', NULL),
  ('STR-021', 'Structure', 'Post-Tension Slab', NULL),
  ('STR-022', 'Structure', 'Precast Slab', NULL),
  ('STR-023', 'Structure', 'Staircase', NULL),
  ('STR-024', 'Structure', 'Ramp', NULL),
  ('STR-025', 'Structure', 'Roof Slab', NULL),
  ('STR-026', 'Structure', 'Structural Steel Column', NULL),
  ('STR-027', 'Structure', 'Structural Steel Beam', NULL),
  ('STR-028', 'Structure', 'Truss', NULL),
  ('STR-029', 'Structure', 'Bracing', NULL),
  ('STR-030', 'Structure', 'Anchor Bolt', NULL),
  ('STR-031', 'Structure', 'Base Plate', NULL),
  ('STR-032', 'Structure', 'Rebar Reinforcement', NULL),
  ('STR-033', 'Structure', 'Formwork', NULL),
  ('STR-034', 'Structure', 'Embedded Plate', NULL),
  ('STR-035', 'Structure', 'Expansion Joint', NULL),
  ('STR-036', 'Structure', 'Construction Joint', NULL),
  ('STR-037', 'Structure', 'Parapet Structure', NULL),
  ('STR-038', 'Structure', 'Water Tank Structure', NULL),
  ('STR-039', 'Structure', 'Lift Pit', NULL),
  ('STR-040', 'Structure', 'Sump Pit', NULL),
  ('ARC-001', 'Archiecture', 'Brick Wall', NULL),
  ('ARC-002', 'Archiecture', 'Block Wall', NULL),
  ('ARC-003', 'Archiecture', 'Partition Wall', NULL),
  ('ARC-004', 'Archiecture', 'Curtain Wall', NULL),
  ('ARC-005', 'Archiecture', 'Glass Wall', NULL),
  ('ARC-006', 'Archiecture', 'Cladding', NULL),
  ('ARC-007', 'Archiecture', 'Plaster Finish', NULL),
  ('ARC-008', 'Archiecture', 'Paint Finish', NULL),
  ('ARC-009', 'Archiecture', 'Tile Finish', NULL),
  ('ARC-010', 'Archiecture', 'Stone Finish', NULL),
  ('ARC-011', 'Archiecture', 'Floor Finish', NULL),
  ('ARC-012', 'Archiecture', 'Raised Floor', NULL),
  ('ARC-013', 'Archiecture', 'Ceiling', NULL),
  ('ARC-014', 'Archiecture', 'Suspended Ceiling', NULL),
  ('ARC-015', 'Archiecture', 'Gypsum Ceiling', NULL),
  ('ARC-016', 'Archiecture', 'Acoustic Ceiling', NULL),
  ('ARC-017', 'Archiecture', 'Door', NULL),
  ('ARC-018', 'Archiecture', 'Fire Rated Door', NULL),
  ('ARC-019', 'Archiecture', 'Window', NULL),
  ('ARC-020', 'Archiecture', 'Louvers', NULL),
  ('ARC-021', 'Archiecture', 'Handrail', NULL),
  ('ARC-022', 'Archiecture', 'Guardrail', NULL),
  ('ARC-023', 'Archiecture', 'Stair Finishing', NULL),
  ('ARC-024', 'Archiecture', 'Skirting', NULL),
  ('ARC-025', 'Archiecture', 'Waterproofing', NULL),
  ('ARC-026', 'Archiecture', 'Roof Waterproofing', NULL),
  ('ARC-027', 'Archiecture', 'Insulation', NULL),
  ('ARC-028', 'Archiecture', 'Thermal Insulation', NULL),
  ('ARC-029', 'Archiecture', 'Acoustic Insulation', NULL),
  ('ARC-030', 'Archiecture', 'Expansion Joint Cover', NULL),
  ('ARC-031', 'Archiecture', 'Sealant', NULL),
  ('ARC-032', 'Archiecture', 'FaÃ§ade System', NULL),
  ('ARC-033', 'Archiecture', 'Canopy', NULL),
  ('ARC-034', 'Archiecture', 'Roof Tile', NULL),
  ('ARC-035', 'Archiecture', 'False Ceiling Panel', NULL),
  ('ARC-036', 'Archiecture', 'Built-in Furniture', NULL),
  ('ARC-037', 'Archiecture', 'Sanitary Partition', NULL),
  ('ARC-038', 'Archiecture', 'Signage', NULL),
  ('ARC-039', 'Archiecture', 'External Works Finishes', NULL),
  ('ARC-040', 'Archiecture', 'Landscape Elements', NULL),
  ('MEP-001', 'MEP', 'Transformer', 'ELECTRICAL (ELV + Power)'),
  ('MEP-002', 'MEP', 'Generator', 'ELECTRICAL (ELV + Power)'),
  ('MEP-003', 'MEP', 'Main Distribution Board', 'ELECTRICAL (ELV + Power)'),
  ('MEP-004', 'MEP', 'Sub Distribution Board', 'ELECTRICAL (ELV + Power)'),
  ('MEP-005', 'MEP', 'Cable Tray', 'ELECTRICAL (ELV + Power)'),
  ('MEP-006', 'MEP', 'Cable Ladder', 'ELECTRICAL (ELV + Power)'),
  ('MEP-007', 'MEP', 'Power Cable', 'ELECTRICAL (ELV + Power)'),
  ('MEP-008', 'MEP', 'Lighting Fixture', 'ELECTRICAL (ELV + Power)'),
  ('MEP-009', 'MEP', 'Emergency Lighting', 'ELECTRICAL (ELV + Power)'),
  ('MEP-010', 'MEP', 'Socket Outlet', 'ELECTRICAL (ELV + Power)'),
  ('MEP-011', 'MEP', 'Switch', 'ELECTRICAL (ELV + Power)'),
  ('MEP-012', 'MEP', 'Earthing System', 'ELECTRICAL (ELV + Power)'),
  ('MEP-013', 'MEP', 'Lightning Protection', 'ELECTRICAL (ELV + Power)'),
  ('MEP-014', 'MEP', 'UPS System', 'ELECTRICAL (ELV + Power)'),
  ('MEP-015', 'MEP', 'Solar Panel System', 'ELECTRICAL (ELV + Power)'),
  ('MEP-020', 'MEP', 'Chiller', 'MECHANICAL (HVAC)'),
  ('MEP-021', 'MEP', 'Cooling Tower', 'MECHANICAL (HVAC)'),
  ('MEP-022', 'MEP', 'AHU (Air Handling Unit)', 'MECHANICAL (HVAC)'),
  ('MEP-023', 'MEP', 'FCU (Fan Coil Unit)', 'MECHANICAL (HVAC)'),
  ('MEP-024', 'MEP', 'Duct', 'MECHANICAL (HVAC)'),
  ('MEP-025', 'MEP', 'Flexible Duct', 'MECHANICAL (HVAC)'),
  ('MEP-026', 'MEP', 'Damper', 'MECHANICAL (HVAC)'),
  ('MEP-027', 'MEP', 'Diffuser', 'MECHANICAL (HVAC)'),
  ('MEP-028', 'MEP', 'Exhaust Fan', 'MECHANICAL (HVAC)'),
  ('MEP-029', 'MEP', 'Ventilation Fan', 'MECHANICAL (HVAC)'),
  ('MEP-030', 'MEP', 'Refrigerant Pipe', 'MECHANICAL (HVAC)'),
  ('MEP-040', 'MEP', 'Water Tank', 'PLUMBING & DRAINAGE'),
  ('MEP-041', 'MEP', 'Booster Pump', 'PLUMBING & DRAINAGE'),
  ('MEP-042', 'MEP', 'Water Supply Pipe', 'PLUMBING & DRAINAGE'),
  ('MEP-043', 'MEP', 'Drainage Pipe', 'PLUMBING & DRAINAGE'),
  ('MEP-044', 'MEP', 'Soil Pipe', 'PLUMBING & DRAINAGE'),
  ('MEP-045', 'MEP', 'Vent Pipe', 'PLUMBING & DRAINAGE'),
  ('MEP-046', 'MEP', 'Floor Trap', 'PLUMBING & DRAINAGE'),
  ('MEP-047', 'MEP', 'Cleanout', 'PLUMBING & DRAINAGE'),
  ('MEP-048', 'MEP', 'Manhole', 'PLUMBING & DRAINAGE'),
  ('MEP-049', 'MEP', 'Grease Trap', 'PLUMBING & DRAINAGE'),
  ('MEP-050', 'MEP', 'Sewage Treatment Plant', 'PLUMBING & DRAINAGE'),
  ('MEP-060', 'MEP', 'Fire Pump', 'FIRE FIGHTING'),
  ('MEP-061', 'MEP', 'Fire Tank', 'FIRE FIGHTING'),
  ('MEP-062', 'MEP', 'Sprinkler Head', 'FIRE FIGHTING'),
  ('MEP-063', 'MEP', 'Fire Hose Reel', 'FIRE FIGHTING'),
  ('MEP-064', 'MEP', 'Hydrant', 'FIRE FIGHTING'),
  ('MEP-065', 'MEP', 'Fire Extinguisher', 'FIRE FIGHTING'),
  ('MEP-066', 'MEP', 'Fire Alarm Panel', 'FIRE FIGHTING'),
  ('MEP-067', 'MEP', 'Smoke Detector', 'FIRE FIGHTING'),
  ('MEP-068', 'MEP', 'Heat Detector', 'FIRE FIGHTING'),
  ('MEP-080', 'MEP', 'CCTV Camera', 'ELV (Low Current Systems)'),
  ('MEP-081', 'MEP', 'Access Control', 'ELV (Low Current Systems)'),
  ('MEP-082', 'MEP', 'PA System', 'ELV (Low Current Systems)'),
  ('MEP-083', 'MEP', 'Data Network Rack', 'ELV (Low Current Systems)'),
  ('MEP-084', 'MEP', 'Telephone System', 'ELV (Low Current Systems)'),
  ('MEP-085', 'MEP', 'Fiber Optic Cable', 'ELV (Low Current Systems)'),
  ('MEP-086', 'MEP', 'Server Room Equipment', 'ELV (Low Current Systems)')
ON CONFLICT (element_code) DO UPDATE SET
  category = EXCLUDED.category,
  element_name = EXCLUDED.element_name,
  note = EXCLUDED.note,
  is_active = true,
  updated_at = now();
